version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Lint KarsaJobs UI Dockerfile
          command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push KarsaJobs UI Docker Image
          command: |
            docker build -t ghcr.io/aldisakti2/karsajobs-ui:latest .
            echo $PW_TOKEN | docker login ghcr.io -u aldisakti2 --password-stdin
            docker push ghcr.io/aldisakti2/karsajobs-ui:latest

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui
