version: 2.1
jobs:
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint
    steps:
      - checkout
      - run:
          name: Lint KarsaJobs Dockerfile
          command: |
            hadolint Dockerfile

  test-app:
    docker:
      - image: golang:latest
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push KarsaJobs Docker Image
          command: |
            docker build -t ghcr.io/aldisakti2/karsajobs:latest .
            echo $PW_TOKEN | docker login ghcr.io -u aldisakti2 --password-stdin
            docker push ghcr.io/aldisakti2/karsajobs:latest

workflows:
  version: 2
  build:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
